export const modelResponseSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    restaurantName: { type: ["string", "null"] },
    currencyCode: { type: "string" },
    summary: {
      type: "object",
      additionalProperties: false,
      properties: {
        headline: { type: "string" },
      },
      required: ["headline"],
    },
    visiblePricingSample: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          menuPrice: { type: ["number", "null"] },
          menuPriceUnit: { type: "string", enum: ["glass", "bottle"] },
          estimatedRetail: { type: ["number", "null"] },
        },
        required: ["menuPrice", "menuPriceUnit", "estimatedRetail"],
      },
    },
    recommendations: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          rank: { type: "integer" },
          wineName: { type: "string" },
          extractedText: { type: "string" },
          producer: { type: ["string", "null"] },
          region: { type: ["string", "null"] },
          vintage: { type: ["integer", "null"] },
          varietal: { type: ["string", "null"] },
          menuPrice: { type: ["number", "null"] },
          menuPriceUnit: { type: "string", enum: ["glass", "bottle"] },
          estimatedRetail: { type: ["number", "null"] },
          scores: {
            type: "object",
            additionalProperties: false,
            properties: {
              markupFairness: { type: ["integer", "null"] },
              producerPedigree: { type: ["integer", "null"] },
              menuStandout: { type: ["integer", "null"] },
              crowdAppeal: { type: ["integer", "null"] },
              personalFit: { type: ["integer", "null"] },
            },
            required: [
              "markupFairness",
              "producerPedigree",
              "menuStandout",
              "crowdAppeal",
              "personalFit",
            ],
          },
          why: { type: "string" },
        },
        required: [
          "rank",
          "wineName",
          "extractedText",
          "producer",
          "region",
          "vintage",
          "varietal",
          "menuPrice",
          "menuPriceUnit",
          "estimatedRetail",
          "scores",
          "why",
        ],
      },
    },
    categoryRecommendations: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          key: { type: "string" },
          title: { type: "string" },
          recommendations: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                rank: { type: "integer" },
                wineName: { type: "string" },
                extractedText: { type: "string" },
                producer: { type: ["string", "null"] },
                region: { type: ["string", "null"] },
                vintage: { type: ["integer", "null"] },
                varietal: { type: ["string", "null"] },
                menuPrice: { type: ["number", "null"] },
                menuPriceUnit: { type: "string", enum: ["glass", "bottle"] },
                estimatedRetail: { type: ["number", "null"] },
                scores: {
                  type: "object",
                  additionalProperties: false,
                  properties: {
                    markupFairness: { type: ["integer", "null"] },
                    producerPedigree: { type: ["integer", "null"] },
                    menuStandout: { type: ["integer", "null"] },
                    crowdAppeal: { type: ["integer", "null"] },
                    personalFit: { type: ["integer", "null"] },
                  },
                  required: [
                    "markupFairness",
                    "producerPedigree",
                    "menuStandout",
                    "crowdAppeal",
                    "personalFit",
                  ],
                },
                why: { type: "string" },
              },
              required: [
                "rank",
                "wineName",
                "extractedText",
                "producer",
                "region",
                "vintage",
                "varietal",
                "menuPrice",
                "menuPriceUnit",
                "estimatedRetail",
                "scores",
                "why",
              ],
            },
          },
        },
        required: ["key", "title", "recommendations"],
      },
    },
    weakSpots: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          categoryHeader: { type: "string" },
          explanation: { type: "string" },
          reasons: {
            type: "array",
            items: { type: "string" },
          },
          examples: {
            type: "array",
            items: { type: "string" },
          },
        },
        required: ["categoryHeader", "explanation", "reasons", "examples"],
      },
    },
    notes: {
      type: "array",
      items: { type: "string" },
    },
  },
  required: [
    "restaurantName",
    "currencyCode",
    "summary",
    "visiblePricingSample",
    "recommendations",
    "categoryRecommendations",
    "weakSpots",
    "notes",
  ],
} as const;
